# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reply_widget.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_ReplyWidget(object):
    def setupUi(self, ReplyWidget):
        ReplyWidget.setObjectName("ReplyWidget")
        ReplyWidget.resize(385, 108)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(ReplyWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.thumbnail = QtGui.QLabel(ReplyWidget)
        self.thumbnail.setMinimumSize(QtCore.QSize(60, 60))
        self.thumbnail.setMaximumSize(QtCore.QSize(60, 60))
        self.thumbnail.setText("")
        self.thumbnail.setPixmap(QtGui.QPixmap(":/tk_multi_infopanel_reply_widget/default_user.png"))
        self.thumbnail.setScaledContents(True)
        self.thumbnail.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.thumbnail.setObjectName("thumbnail")
        self.verticalLayout_2.addWidget(self.thumbnail)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user = QtGui.QLabel(ReplyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user.sizePolicy().hasHeightForWidth())
        self.user.setSizePolicy(sizePolicy)
        self.user.setStyleSheet("font-weight: bold")
        self.user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user.setWordWrap(True)
        self.user.setObjectName("user")
        self.horizontalLayout.addWidget(self.user)
        self.date = QtGui.QLabel(ReplyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        self.date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date.setWordWrap(True)
        self.date.setObjectName("date")
        self.horizontalLayout.addWidget(self.date)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.reply = QtGui.QLabel(ReplyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reply.sizePolicy().hasHeightForWidth())
        self.reply.setSizePolicy(sizePolicy)
        self.reply.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.reply.setWordWrap(True)
        self.reply.setObjectName("reply")
        self.verticalLayout.addWidget(self.reply)
        self.attachment_header = QtGui.QLabel(ReplyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attachment_header.sizePolicy().hasHeightForWidth())
        self.attachment_header.setSizePolicy(sizePolicy)
        self.attachment_header.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.attachment_header.setWordWrap(True)
        self.attachment_header.setObjectName("attachment_header")
        self.verticalLayout.addWidget(self.attachment_header)
        self.attachment_scrollarea = QtGui.QScrollArea(ReplyWidget)
        self.attachment_scrollarea.setMinimumSize(QtCore.QSize(0, 1))
        self.attachment_scrollarea.setMaximumSize(QtCore.QSize(16777215, 120))
        self.attachment_scrollarea.setFrameShape(QtGui.QFrame.NoFrame)
        self.attachment_scrollarea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.attachment_scrollarea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attachment_scrollarea.setWidgetResizable(True)
        self.attachment_scrollarea.setObjectName("attachment_scrollarea")
        self.attachment_scrollarea_contents = QtGui.QWidget()
        self.attachment_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 287, 26))
        self.attachment_scrollarea_contents.setObjectName("attachment_scrollarea_contents")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.attachment_scrollarea_contents)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.attachment_scrollarea.setWidget(self.attachment_scrollarea_contents)
        self.verticalLayout.addWidget(self.attachment_scrollarea)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ReplyWidget)
        QtCore.QMetaObject.connectSlotsByName(ReplyWidget)

    def retranslateUi(self, ReplyWidget):
        ReplyWidget.setWindowTitle(QtGui.QApplication.translate("ReplyWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.user.setText(QtGui.QApplication.translate("ReplyWidget", "John Smith", None, QtGui.QApplication.UnicodeUTF8))
        self.date.setText(QtGui.QApplication.translate("ReplyWidget", "3 days ago", None, QtGui.QApplication.UnicodeUTF8))
        self.reply.setText(QtGui.QApplication.translate("ReplyWidget", "Reply reply text", None, QtGui.QApplication.UnicodeUTF8))
        self.attachment_header.setText(QtGui.QApplication.translate("ReplyWidget", "Attachments", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
